from __future__ import annotations

from pathlib import Path
from typing import Protocol

from fact_factory.domain.models import (
    Config,
    Fact,
    FactSummary,
    Gap,
    QueryLog,
    ResultType,
    Stats,
)


class InstanceLocator(Protocol):
    def locate(self, start: Path | None = None) -> Path: ...


class ConfigStore(Protocol):
    def load(self, instance_dir: Path) -> Config: ...


class EmbeddingProvider(Protocol):
    def embed(self, text: str) -> bytes: ...


class FactRepository(Protocol):
    def add(self, fact: Fact) -> None: ...

    def get_by_id(self, fact_id: str) -> Fact | None: ...

    def list_all_with_embeddings(self) -> list[Fact]: ...

    def list_page(self, page: int, page_size: int) -> tuple[list[FactSummary], int]: ...

    def search(self, term: str, page: int, page_size: int) -> tuple[list[FactSummary], int]: ...

    def count(self) -> int: ...

    def remove(self, fact_id: str) -> None: ...


class GapRepository(Protocol):
    def add(self, gap: Gap) -> None: ...

    def get_by_id(self, gap_id: str) -> Gap | None: ...

    def list_open(self) -> list[Gap]: ...

    def resolve(self, gap_id: str, resolved_at, resolved_fact_id: str) -> None: ...

    def remove(self, gap_id: str) -> None: ...

    def count(self) -> int: ...

    def count_open(self) -> int: ...

    def count_resolved(self) -> int: ...

    def top_open_subjects(self, limit: int) -> list[tuple[str, int]]: ...


class QueryLogRepository(Protocol):
    def add(self, log: QueryLog) -> None: ...

    def count(self) -> int: ...

    def count_by_result_type(self, result_type: ResultType) -> int: ...

    def top_queries(self, limit: int) -> list[tuple[str, int]]: ...


class InstanceInitializer(Protocol):
    def create(self, target_dir: Path) -> Path: ...


class StatsReader(Protocol):
    def get_stats(self) -> Stats: ...
